services:
  proxy:
    image: caddy
    network_mode: "host"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - freeswitch
  backend:
    restart: always
    image: ghcr.io/tcmzzz/lightcall:master
    network_mode: "host"
    environment:
      - INIT_ADMIN_EMAIL=${INIT_ADMIN_EMAIL}
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./run/pb_data:/app/pb_data
      - ./run/fs-cdr-csv:/cdr-csv:ro
      - ./run/fs-record:/record:ro
      - ./run/cdc:/app/cdc
  freeswitch:
    restart: always
    image: ghcr.io/tcmzzz/freeswitch:v1.10.9
    network_mode: "host"
    volumes:
      - ./run/fs-cdr-csv:/usr/local/freeswitch/log/cdr-csv
      - ./run/fs-record:/usr/local/freeswitch/recordings
      - ./run/fs-cert:/cert
    environment:
      - BACKEND_ADDR=http://127.0.0.1:8090
    healthcheck:
      test: ["CMD-SHELL", "fs_cli -x 'sofia status profile internal' | grep wss"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  # 模拟运营商服务，仅在演示环境中启动
  fakeprovider:
    restart: always
    profiles:
      - demo
    build:
      context: ../dev/fake-privider
      dockerfile: ./Dockerfile
    networks:
      ring-dev-bridge:
        ipv4_address: 192.168.66.30
networks:
  ring-dev-bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: 'nat'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
    ipam:
      config:
        - subnet: "192.168.66.0/24"
          gateway: "192.168.66.1"
